flashcard/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('flashcardApp.urls'))
]

flashcardApp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views
from .views import getFlashcardsView
from django.contrib.auth import views as auth_views

app_name = "flashcardApp"

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('search/', views.search, name='search'),
    path('signIn/', views.user_login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signUp/', views.user_registration, name='registration'),
    path('flashcards/<str:groupId>/', views.flashcard, name='flashcards'),
    path('flashcardGroup/<str:title_pk>/', views.flashcard_group_view, name='flashcardGroup'),
    path('getFlashcards/<str:groupId>', getFlashcardsView.as_view(), name='getFlashcards'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

flashcardApp/models.py
from datetime import datetime

from django.contrib import auth
from django.contrib.auth.models import User, Permission, Group
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    profile_picture = models.ImageField(upload_to='images/', null=True, blank=True)
    groups = models.ManyToManyField(Group, related_name='customuser_set', blank=True, help_text='')
    user_permissions = models.ManyToManyField(Permission, related_name='customuser_set', blank=True, help_text='')


class FlashcardGroup(models.Model):
    title = models.CharField(max_length=250)
    cardQuantity = models.IntegerField(default=0)
    date = models.DateTimeField(default=datetime.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    groupManager = models.Manager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('flashcardApp:flashcardGroup', args=[self.title])


class Flashcard(models.Model):
    word = models.CharField(max_length=250)
    answer = models.CharField(max_length=250)
    group = models.ForeignKey(FlashcardGroup, on_delete=models.CASCADE)
    language = models.CharField(max_length=250, default='')

    flashcardManager = models.Manager()

flashcardApp/forms.py
from django import forms

from flashcardApp.models import FlashcardGroup


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'input'}), label="Login")
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input'}), label="Hasło")


class RegistrationForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'input'}), label="Imię")
    mail = forms.CharField(widget=forms.TextInput(attrs={'class': 'input'}), label="E-mail")
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'input'}), label="Login")
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input'}), label="Hasło")

flashcardApp/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.views import View

from flashcardApp.forms import LoginForm, RegistrationForm
from flashcardApp.models import FlashcardGroup, Flashcard


def index(request):
    return render(request, 'content/index.html')


def user_login(request):
    loginError = False
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect('/')
            else:
                loginError = True
    else:
        form = LoginForm()

    return render(request, 'user/login.html', {'form': form, 'loginError': loginError})


def user_registration(request):
    error = False
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            try:
                User.objects.create_user(
                    username=request.POST.get('username'),
                    email=request.POST.get('email'),
                    password=request.POST.get('password'),
                    first_name=request.POST.get('name'),
                )

            except:
                error = True
        else:
            error = True
    else:
        form = RegistrationForm()

    return render(request, 'user/registration.html', {'form': form, 'error': error})


def create(request):
    if request.method == 'POST':
        lesson_name = request.POST['lesson-name']
        polish_words = request.POST.getlist('polish[]')
        english_words = request.POST.getlist('english[]')
        imagePath = request.POST.get('file-input-name')

        username = request.user.username

        new_flashcard_group = FlashcardGroup.groupManager.create(
            title=lesson_name,
            cardQuantity=len(polish_words),
            author=User.objects.get(username=username),
        )

        for polish, english in zip(polish_words, english_words):
            Flashcard.flashcardManager.create(
                word=polish,
                answer=english,
                group=new_flashcard_group,
                language='Angielski',
            )

        return HttpResponseRedirect('/search/')
    else:
        return render(request, 'content/create.html', {})


def search(request):
    if request.method == 'POST' and request.POST.get('my-groups') == 'True':
        allFlashCardGroups = FlashcardGroup.groupManager.filter(author=request.user.id)
        isMyGroupsTrue = True
    else:
        allFlashCardGroups = FlashcardGroup.groupManager.all()
        isMyGroupsTrue = False

    return render(request, 'content/search.html', {'allGroups': allFlashCardGroups, 'groups_views': isMyGroupsTrue})


def flashcard_group_view(request, title_pk):
    group = get_object_or_404(FlashcardGroup, title=title_pk)
    flashcards = Flashcard.flashcardManager.filter(group=group)
    return render(request, 'content/flashcard-group.html', {'group': group, 'flashcards': flashcards})


def flashcard(request, groupId):
    group = get_object_or_404(FlashcardGroup, title=groupId)
    flashcards = Flashcard.flashcardManager.filter(group=group)
    return render(request, 'content/flashcard.html', {'flashcards': flashcards, 'group': group})


class getFlashcardsView(View):
    def get(self, request, groupId):
        group = get_object_or_404(FlashcardGroup, title=groupId)
        flashcardsJson = Flashcard.flashcardManager.filter(group=group).values()

        return JsonResponse({'flashcardsJson': list(flashcardsJson)})

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block page_title %} {% endblock %} </title>
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&amp;display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
    {% block links %}{% endblock %}
</head>
<body>
    <header>
        <img src="{% static 'foto/logo.png' %}" alt="">

        <ul>
            <li><a href="{% url 'flashcardApp:index' %}">Home</a></li>
            <li><a href="{% url 'flashcardApp:create' %}">Stwórz</a></li>
            <li><a href="{% url 'flashcardApp:search' %}">Szukaj</a></li>

            {% if user.is_authenticated %}
                <li>
                    <form method="post" action="{% url 'flashcardApp:logout' %}">
                        {% csrf_token %}
                        <button type="submit">Wyloguj</button>
                    </form>
                </li>
            {% else %}
                <li><a href="{% url 'flashcardApp:login' %}">Zaloguj się</a></li>
            {% endif %}
        </ul>
    </header>

    <br>

    <main class="app">
        {% block content %}  {% endblock %}
    </main>

    <br><br><br>

    <footer>
        <h1>TUTAJ BĘDZIE STOPKA <br> - [ 'KIEDYŚ' ] <br> - [ 'MOŻE' ]</h1>
        <br>
        <hr>
        <br><br>
        <span>
            Designe by: <b>Mateusz Maniak,<br> Szymon Szymański & Ernest Sapijaszko</b>
        </span>
    </footer>

    {% block scripts %}  {% endblock %}
</body>
</html>

templates/content/create.html
{% extends 'base.html' %}
{% load static %}

{% block page_title %} Stwórz własny zbiór fiszek {% endblock %}
{% block links %} <link rel="stylesheet" href="{% static 'css/create.css' %}"> {% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <h1>Stwórz</h1>
            <br>
            <span>Rozpocznij swoją przygodę z nauką języka angielskiego, tworząc własny zbiór fiszek! Personalizuj swoje materiały, dziel się nimi z innymi uczniami lub nauczycielami. Z nami nauka stanie się nie tylko efektywna, ale także fascynująca!</span>

            <br><br><hr><br>
            <div class="group-name">
                <h2>Nazwa lekcji:</h2>
                <input type="text" name="lesson-name" class="lesson-name" id="">
            </div>

            <br><br>
            <h2>Słówka:</h2>
            <table id="table">
                <tbody id="tbody">
                    <tr>
                        <td><span title="język polski" style="background-image: url('https://static.fiszkoteka.pl/imgmrg/P/g/o/HISi51swR0_MKo-Bv.png');background-position:-0px -0px;width:32px;height:22px;vertical-align: middle;overflow:hidden;display:inline-block;"></span> <br><br>  Polski</td>
                        <td><b>-</b></td>
                        <td><span title="English" style="background-image: url('https://static.fiszkoteka.pl/imgmrg/P/g/o/HISi51swR0_MKo-Bv.png');background-position:-32px -0px;width:32px;height:22px;vertical-align: middle;overflow:hidden;display:inline-block;"></span> <br><br>  Angielski</td>
                        <td><i class="bi bi-x-lg"></i> <br><br> Usuń</td>
                    </tr>

                    <tr>
                        <td><input type="text" name="polish[]" id=""></td>
                        <td><b>-</b></td>
                        <td><input type="text" name="english[]" id=""></td>
                        <td><i class="bi bi-trash" onclick="deleteWord(this)"></i></td>
                    </tr>

                    <tr>
                        <td><input type="text" name="polish[]" id=""></td>
                        <td><b>-</b></td>
                        <td><input type="text" name="english[]" id=""></td>
                        <td><i class="bi bi-trash" onclick="deleteWord(this)"></i></td>
                    </tr>

                    <tr>
                        <td><input type="text" name="polish[]" id=""></td>
                        <td><b>-</b></td>
                        <td><input type="text" name="english[]" id=""></td>
                        <td><i class="bi bi-trash" onclick="deleteWord(this)"></i></td>
                    </tr>
                </tbody>
            </table>
            <button class="add-word" type="button" onclick="addWord()">Dodaj Słowo</button>
            <hr><br>
            <input type="submit" class="upload"  value="Udostępnij">
            <script src="{% static 'js/addWord.js' %}"></script>
        </form>
        <script>
            function updateFileName(input) {
                document.getElementById('fileSelected').innerText = input.files[0].name;
            }
        </script>
    {% else %}
        <script>
            window.location.href = '/signIn/';
        </script>
    {% endif %}
{% endblock %}

templates/content/flashcard-group.html
{% extends 'base.html' %}
{% load static %}

{% block page_title %} {{ title }} {% endblock %}
{% block links %}
    <link rel="stylesheet" href="{% static 'css/create.css' %}">
    <link rel="stylesheet" href="{% static 'css/flashcard-group.css' %}">
{% endblock %}

{% block content %}
    <div class="group-info">
        <h1>{{ group.title }}</h1>
        <div class="date-user">
            <p>Data: <i><b>{{ group.date }}</b></i>, </p>
            <p>Autor: <b>{{ group.author }}</b></p>
        </div>
        <br>
        <a href="{% url 'flashcardApp:flashcards' group.title %}">Rozpocznij naukę!</a>
    </div>
     <br><br><br><hr><br><br>
     <div class="words-group">
         <h3>Lista słówek: </h3>
         <table id="table">
             <tbody id="tbody">
             <tr>
                 <td><span title="język polski" style="background-image: url('https://static.fiszkoteka.pl/imgmrg/P/g/o/HISi51swR0_MKo-Bv.png');background-position:-0px -0px;width:32px;height:22px;vertical-align: middle;overflow:hidden;display:inline-block;"></span> <br><br>  Polski</td>
                 <td><b>-</b></td>
                 <td><span title="English" style="background-image: url('https://static.fiszkoteka.pl/imgmrg/P/g/o/HISi51swR0_MKo-Bv.png');background-position:-32px -0px;width:32px;height:22px;vertical-align: middle;overflow:hidden;display:inline-block;"></span> <br><br>  Angielski</td>
             </tr>

                 {% for flaschcard in flashcards %}
                     <tr>
                        <td>{{ flaschcard.word }}</td>
                        <td><b>-</b></td>
                        <td>{{ flaschcard.answer }}</td>
                    </tr>
                 {% endfor %}
             </tbody>
         </table>
     </div>
{% endblock %}

templates/content/flashcard.html
{% extends 'base.html' %}
{% load static %}

{% block page_title %} Flashcards {% endblock %}
{% block links %}
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
    <link rel="stylesheet" href="{% static 'css/flashcard.css' %}">
{% endblock %}

{% block content %}
    <div class="card" id="flashcard">
        <div class="card-inner">
            <div class="front">
                <p><i>J. Polski</i></p>
                <h3 id="word"></h3>
                <hr><br>
                <input type="text" id="userAnswer">
                <br><br>
                <button onclick="flipCard()" id="checkAnswer">Pokaż odpowiedź</button>
            </div>
            <div class="back">
                <p><i>J. Angielski</i></p>
                <h3 id="answer"></h3>
                <hr><br>
                <input type="text" class="answer correct" id="inputAnswer">
                <br><br>
                <button onclick="flipCard(); cos()">Pokaż J. Angielski</button>
                <br><br>
                <button id="dalejButton" onclick="flipCard()">Dalej</button>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script>
        let word = document.getElementById('word');
        let answer = document.getElementById('answer');
        let run = true;
        let index = 0;

        $(document).ready(function () {
            $.ajax({
                url: '/getFlashcards/' + encodeURIComponent('{{ group.title }}'),
                type: 'GET',
                dataType: 'json',
                success: function (data) {
                    let index = 0;
                    let userAnswer = document.getElementById('userAnswer');
                    let inputAnswer = document.getElementById('inputAnswer');

                    const delay = (delayInms) => {
                        return new Promise(resolve => setTimeout(resolve, delayInms));
                    };

                    async function nextFlashcard() {
                        await delay(500);
                        if (run) {
                            const element = data.flashcardsJson[index];

                            word.innerText = element.word;
                            answer.innerText = element.answer;

                            run = false;

                            $('#checkAnswer').on('click', function (){
                                inputAnswer.value = userAnswer.value;

                                if(inputAnswer.value.toLowerCase() === element.answer.toLowerCase()){
                                    inputAnswer.style.border = "green 3px solid";
                                }else{
                                    inputAnswer.style.border = "red 3px solid";
                                }
                            })

                            index++;
                        }
                    }

                    $('#dalejButton').on('click', function () {
                        if (!data.flashcardsJson[index + 1]) {
                            document.getElementById('dalejButton').innerText = "Zakończ";
                            $('#dalejButton').on('click', function () {
                                window.location.replace("/search/");
                            });
                        }

                        userAnswer.value = '';
                        inputAnswer.value = '';

                        run = true;
                        nextFlashcard();
                    });

                    nextFlashcard();
                },
            });
        });
    </script>

    <script src="{% static 'js/cardFlip.js' %}"></script>
{% endblock %}

templates/content/index.html
{% extends 'base.html' %}
{% load static %}

{% block page_title %} Strona główna {% endblock %}
{% block links %} <link rel="stylesheet" href="{% static 'css/index.css' %}"> {% endblock %}

{% block content %}
    <div class="row">
            <div class="text">
                <div class="title">
                    Zacznij od Podstaw:
                </div>
                <div class="content">
                    Rozpocznij swoją przygodę z językiem angielskim od podstaw. Nasza platforma oferuje setki fiszek, które pomogą Ci opanować podstawowe słownictwo, gramatykę i zwroty. Niezależnie od tego, czy jesteś początkującym, czy chcesz odświeżyć swoje umiejętności, mamy materiały dostosowane do Twoich potrzeb.
                </div>
            </div>
            <div class="image">
                <img src="{% static 'foto/index_foto3.jpg' %}">
            </div>
        </div>

        <div class="row">
            <div class="text">
                <div class="title">
                    Twórz i Dziel się Fiszkami:
                </div>
                <div class="content">
                    Nie tylko ucz się, ale także twórz własne fiszki! Dodawaj słówka, zwroty czy zdania, które sprawiają Ci trudność. Dzięki naszym narzędziom możesz personalizować fiszki zgodnie z Twoimi potrzebami. Co więcej, możesz je udostępniać innym, abyście razem mogli rozwijać swoje umiejętności językowe.
                </div>
            </div>
            <div class="image">
                <img src="{% static 'foto/index_foto2.jpg' %}">
            </div>
        </div>

        <div class="row">
            <div class="text">
                <div class="title">
                    Nauka w Dowolnym Miejscu i Czasie:
                </div>
                <div class="content">
                    Nasza platforma jest dostępna online, co oznacza, że możesz uczyć się w dowolnym miejscu i czasie. Czy to w drodze do szkoły, w przerwie obiadowej czy wieczorem przed snem, masz dostęp do swoich fiszek. Nauka staje się bardziej elastyczna i dostosowana do Twojego stylu życia.
                </div>
            </div>
            <div class="image">
                <img src="{% static 'foto/index_foto1.jpg' %}">
            </div>
        </div>

        <div class="row">
            <div class="text">
                <div class="title">
                    Narzędzia dla Nauczycieli:
                </div>
                <div class="content">
                    Jesteś nauczycielem? Nasza platforma oferuje narzędzia do tworzenia fiszek dla Twoich uczniów. Monitoruj ich postępy, dostosowuj materiały do programu nauczania i wspieraj ich rozwój językowy.
                </div>
            </div>
            <div class="image">
                <img src="{% static 'foto/index_foto4.jpg' %}">
            </div>
        </div>

        <br>
        <br><br><br>

        <h1>Dlaczego warto wybrać naszą platformę</h1>
        <br><hr><br>
        <div class="grid-container">
            <div class="grid-item">
                <i class="bi bi-1-circle"></i>
                <br>
                Elastyczność Nauki
            </div>
            <div class="grid-item">
                <i class="bi bi-2-circle"></i>
                <br>
                Personalizowane Fiszki
            </div>
            <div class="grid-item">
                <i class="bi bi-3-circle"></i>
                <br>
                Promowanie Uczenia się
            </div>
            <div class="grid-item">
                <i class="bi bi-4-circle"></i>
                <br>
                Łatwość Używania
            </div>
        </div>
        <br>
        <br>
        <a href="{% url 'flashcardApp:search' %}" class="start-learn">Zacznij naukę teraz!</a>

{% endblock %}

templates/content/search.html
{% extends 'base.html' %}
{% load static %}

{% block page_title %} Szukaj {% endblock %}
{% block links %}
    <link rel="stylesheet" href="{% static 'css/search.css' %}">
    <script src="{% static "js/searchBox.js" %}"></script>
{% endblock %}

{% block content %}
    <div class="searchBox">
        <h1 class="search-h1">Szukaj:</h1>
        <form action="" method="post">
            {% csrf_token %}
            <input type="text" class="search-input" placeholder="Wyszkuja grupę fiszke po tytule." id="search-box">
            {% if user.is_authenticated %}
                {% if groups_views %}
                    <input type="hidden" name="my-groups" value="False">
                    <input type="submit" value="Pokaż wszystkie fiszki">
                {% else %}
                    <input type="hidden" name="my-groups" value="True">
                    <input type="submit" value="Pokaż moje fiszki">
                {% endif %}
            {% endif %}
        </form>
    </div>

    <br><br><hr><br>

    <div class="search-result">
        {% for group in allGroups %}
            <a href="{{ group.get_absolute_url }}" class="element">
                <div class="text-info">
                    <h2 class="title">{{ group.title }}</h2>
                    <div class="element-info">
                        <div>
                            <i class="quantity">Ilość fiszek: <b>{{ group.cardQuantity }}</b></i>,<br>
                            <span class="date">{{ group.date }}</span>
                        </div>
                        <span class="user">
                            <i class="bi bi-person-circle"></i>
                            <b><i>{{ group.author }}</i></b>
                        </span>
                    </div>
                </div>
            </a>
        {% endfor %}
    </div>
{% endblock %}

templates/user/login.html
{% extends 'base.html' %}
{% load static %}

{% block page_title %} Login {% endblock %}
{% block links %} <link rel="stylesheet" href="{% static 'css/login.css' %}"> {% endblock %}

{% block content %}
    <div class="app">
        <div class="logo">
            <img src="{% static 'foto/logo.png' %}" alt="logo">
        </div>
        <form action="" class="form" method="post">
            <h1>Zaloguj się</h1>
            {% if loginError %}
                <h3>Nieprawidłowe dane logowania</h3>
            {% endif %}
            {% csrf_token %}
            {{ form.as_p }}
            <br>
            <input type="submit" class="btn submit" value="Zaloguj się">
            <br>
            <a href="{% url 'flashcardApp:registration' %}">Stwórz konto</a>
        </form>
    </div>
{% endblock %}

templates/user/registration.html
{% extends 'base.html' %}
{% load static %}

{% block page_title %} Rejestracja {% endblock %}
{% block links %} <link rel="stylesheet" href="{% static 'css/login.css' %}"> {% endblock %}

{% block content %}

    <div class="app">
        <div class="logo">
            <img src="{% static 'foto/logo.png' %}" alt="logo">
        </div>
        <form action="" class="form" method="post">
            <h1>Stwórz konto</h1>
            {% if error %}
                <p style="color: red"><b>Formularz został wypełniony nieprawidłowo</b></p>
            {% endif %}
            {% csrf_token %}
            {{ form.as_p }}
            <br>
            <input type="submit" class="btn submit" value="Załóż konto">
            <br>
            <a href="">Zaloguj się</a>
        </form>
    </div>
{% endblock %}